### ISSUE TITLE
Mono YAML file so small dataset

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#113]
Depends and basing on #167
If we read YAML with `com.github.vkorobkov.jfixtures.util.YmlUtil#load` then we can just _pass_ the output map into #167 

For medium sized datasets(a few small tables) it may be the most valuable option to put the data into a single YAML file, so no need to think about directory structure:
```yaml
# users table
users:
  homer:
    name: Homer
    age: 40
  bart:
    name: Bart
    age: 12

# admin.roles table
# beware the dots in table name should be escaped
"admin.roles": 
  admin:
    reads: true
    writes: true
  user:
    reads: true
    writes: false
```
