### ISSUE TITLE
A WIKI page for tables inheritance

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#114]
Some renaming may be required, needs a revisit. 

## The original docs:
It happens that designing the database we can set some conventions - for example, in many cases we want to add
a versioning support for a few/all tables. In the very basic case it means that every row in such table(s)
has a field called `version` and has some numeric type. By default it might equal to `1`, for instance, and on every
row modification it gets incremented:
```yaml
vlad:
  name: Vlad
  role: dev
  version: 1
alex:
  name: Alexander
  role: ui
  version: 1
dimon:
  name: Diman
  role: qa
  version: 1
```
`version: 1` was duplicated 3 times - for every single row. It might be convenient when you have 3 rows, but when
you have, for example, 300 rows, it makes sense to avoid such duplicates for every single row. There are two ways of
doing so: 
1. Set the default value for `version` column on the DB level 
2. Use inheritance on JFixtures side, e.g. to add some shared behaviour for every row of a table or tables.

The first variant is preferable, of course - it is simple and natural for relational databases, does not need any
extra knowledge or skills to implement it. However, due to some reasons, your DB design might not have the default
values for cases like that: for example, if the architect or DBA prefer to set these values explicitly from your app,
or if it is a legacy problem and the DB refactoring is risky/going to take much/etc or when you need to put values
which are different from table's default values in SQL.

So for the second case JFixtures allows you to inherit tables. If we create a `.conf.yml` and put in it following
lines:
```yaml
columns:
  concerns:
    has_version:
      version: 1

  apply:
    every_table_has_version:
      to: /.+
      concerns: has_version
```
then we can simplify our fixtures and remove `version: 1` from every single row:
```yaml
vlad:
  name: Vlad
  role: dev
alex:
  name: Alexander
  role: ui
dimon:
  name: Diman
  role: qa
```
So how does it work?

`columns` section in `.conf.yml` is responsible for tables inheritance. It consists of two main subsections:
`concerns` and `apply`. 

`concerns` just describes behaviours which could be added to tables, like `has_version` behaviour in our case. 
It has exactly the same format as rows in the fixtures. `has_version` concern sets column named `version` to `1` 
for every row. 

`apply` section defines which concerns should be applied to which tables: `to: /.+` means "apply to every table", 
`concerns: has_version` specified which concern or concerns to apply.

It is possible to apply many concerns to many tables at the same time: sections `apply:to` and `apply:concerns` can
receive many items(tables and concerns):

* A single value: `to: users`, `concerns: has_version`
Applies to a single table/concern
* Comma separated string: `to: table_1, table_2, table_3`, `concerns: has_version, has_cr_date`
Applies to every comma-separated table/concern.
* An array: `to: [table_1, table_2, table_3]`, `concerns: [has_version, has_cr_date]`.
Array could also contain another arrays. The depth in not limited.
Every array(or sub array) item could be either a string(for one table/concern) or a comma separated string(
for many tables/concerns). This pattern opens a very powerful ability of YAML: you can define and include lists into 
one another if you need to group and reuse items:
```yaml
columns:
  concerns:
    has_version:
      version: 1
      
  # Define a list to reuse it later
  _user_related_tables: &user_related_tables
    - users
    - profiles
    - avatars
    - raitings

  apply:
    every_table_has_version:
      # applies to every table from user_related_tables list and to comments and tickets
      to: [*user_related_tables, comments, tickets]
      concerns: has_version
    # every_table_has_cr_date ...
    # etc 
```

The items of `apply:to` could be a either a string or a regular expression. 
Use `/` prefix to start a regexp: `to: /.+` means `.+` will be tested against every table, and when table name matches, 
all the concerns from `concerns` section will be applied.

The order of items in `apply:to` does not matter; any duplicates are ignored;
The order of items in `apply:concerns` matters: concerns will be applied in the same order as they were defined,
from left to right. Duplicates are not getting removed. When many concerns, they are getting merged, it means, 
that the further concerns complement(add rows) or override(replace rows) the previous ones.

Note, that columns in fixtures have a priority over the columns from `columns:concerns`. It means that when
fixture defines the same columns as defined in `columns:concerns` for that table, the column value from
fixture will override the value from `columns:concerns`.

The `apply` may have a number of named subsections like `every_table_has_version`, `user_table_has_cr_date`, etc.
These named sections are getting scanned and applied in top down order:
```yaml
columns:
  concerns:
    has_version:
      version: 1
      
    has_cr_date:
      cr_date: NOW()
      
    has_next_version:
      version: 2

  apply:
    # Adds [version: 1] to every row of users table
    users_has_version:
      to: users
      concerns: has_version
    # Adds [cr_date: NOW()] to every row of users table, keeping previous [version: 1]
    users_has_cr_date:
      to: users
      concerns: has_cr_date
    # Replaces [version: 1] with [version: 2]   
    users_has_version_2:
      to: users
      concerns: has_next_version
```
This example results into two columns, which will be added into every row of `users` table: 
`cr_date: NOW()` and `version: 2`
