### ISSUE TITLE
Configuration profiles

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#200]
# Configuration profiles

## Problem: 
Different kind of tests, for example, integration and unit tests may have common and different parts in the configuration. 

The relations between the tables, which are defined in “refs” section, are normally do not depend on the test type and therefore are always the same. This is a good example of the common part in the settings which never should be changed.

Table cleanup policies, for instance, may depend on the test type: integration tests may need data clean up in the very beginning to remove the previous test data first. Unit tests, instead, normally do not need data cleanup since every such test in running in it’s own isolated transaction which reverts all the test data and the changed that were made in the test.

There are also maybe a combination of two: before all unit tests user may want to load some global and shared data(with clean up in the beginning), but every single test method may append it’s own small temporary dataset in the scope of the belonging transaction(that does not require table cleanup)

Therefore, a simple and elegant mechanism of splitting different parts in configuration is required.

## Solution
We may introduce “profiles” concept into our configuration using YAML inheritance mechanism:
* https://stackoverflow.com/questions/14184971/more-complex-inheritance-in-yaml?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa 
* https://learnxinyminutes.com/docs/yaml/ 

When building JFixtures, user may specified the specific profile(or do not specify any to use the default one):
```java
JFixtures
  .withConfig(“/config.yml”)
  .withProfile(“units”)
  .loadDirectory(“/home/fixtures”)
  .compile()
```

YAML with profile may look like:

```yaml
profiles:
  # Default profile
  default: &default_profile
    tables:
      default_cleanup:
        applies_to: “/+“
        clean_method: delete

    refs:
      users:
        profile_id: "profiles"

  # Profile for unit tests
  units:
    <<: *default_profile # inheriting the default profile

    # disabling tables cleanup
    tables:
      default_cleanup:
        applies_to: “/+“
        clean_method: none
```

Note that the old YAML structure without profiles should be supported as well. 

When the profile is “default”, then:
1. Section “profiles.default” should be checked, and if exists, should be considered as the root section
2. If “profiles.default” does not exist, using the root of the document

When the profile is other that “default”, for instance, “units” then:
1. Section “profiles.units” should be checked, and if exists, should be considered as the root section
2. If “profiles.units” does not exist then an exception should be raised saying the specified profile was not found in the configuration

Implementation:
From the interface level, JFixtures class should provide methods for specifying profiles:
* `withProfile(String profile);`
* `withDefaultProfile();  // calls internally <return withProfile(“default”)>`

Probably `com.github.vkorobkov.jfixtures.config.ConfigLoader` should take care of the rest of the logic: selecting the config root path.
