### ISSUE TITLE
Table property for disabling cleanup

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#21]
By now JFixtures generates clean up SQL for every table(before inserts):
```sql
DELETE FROM $table_name;
```
This behavior is hardcoded but should be switchable off. A new table property is required:
```yaml
tables:
   no_clean_up:
     applies_to: /.+
     clean_method: none # might be delete or truncate(truncate is out of scope of this ticket)
```

See `com.github.vkorobkov.jfixtures.processor.Processor#cleanupTable`
