### ISSUE TITLE
truncate clean up method

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#22]
By now JFixtures generates clean up SQL for every table(before inserts):
```sql
DELETE FROM $table_name;
```

Add ability to change the instruction from `DELETE` to `TRUNCATE` in order to produce SQL like:
```sql
TRUNCATE $table_name;
```

A new table property is required:
```yaml
tables:
   no_clean_up:
     tables: /.+
     clean_method: truncate # might be delete or none
```
