### ISSUE TITLE
Before inserts custom SQL

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#27]
Problem:
To be able to write a custom SQL before insert instructions(and after cleanup instruction).

Possible configuration:
```yaml
tables:
  transactional_users:
    applies_to: users, users_profiles
    before_inserts:
      - // Doing table $TABLE_NAME
      - BEGIN TRANSACTION;
```

The `before-insert` section could be: a single value or a list(or list of lists with any depth). The `$TABLE_NAME` placeholder should be replaced with the real table name.

Before-insert instructions order must not be changed, duplicates(if there are) must not be removed.
