### ISSUE TITLE
After inserts custom SQL

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#28]
Problem:
To be able to write a custom SQL after the insert instructions
Possible configuration:
```yaml
tables:
  transactional_users:
    applies_to: users, users_profiles
    after_inserts:
      - // Completed table $TABLE_NAME
      - COMMIT TRANSACTION;
```

The `after-insert` section could be: a single value or a list(or list of lists with any depth). The `$TABLE_NAME` placeholder should be replaced with the real table name.

The instructions order must not be changed, duplicates(if there are) must not be removed.
