### ISSUE TITLE
Before cleanup custom SQL

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#29]
Problem:
To be able to write a custom SQL before the cleanup instruction(if disabled, then before-cleanup means the same as before-inserts):
Possible configuration:
```yaml
tables:
  transactional_users:
    applies_to: users, users_profiles
    before-cleanup:
      - // Beginning of the $TABLE_NAME
      - BEGIN TRANSACTION;
```

The `before-cleanup` section could be: a single value or a list(or list of lists with any depth). The `$TABLE_NAME` placeholder should be replaced with the real table name.

The instructions order must not be changed, duplicates(if there are) must not be removed.
