### ISSUE TITLE
Remove `type:sql` for column values

### ISSUE THREAD

**Issue by vkorobkov** [vkorobkov/jfixtures#36]
Currently when we don't want to escape a string we use `type: sql` in column values in fixture files:
```yaml
vlad:
  age: 29
  name: Vlad # Gets escaped
dan:
  age: 45
  name:
    type:  value
    value: Dan # Gets escaped because of type: value
robot:
  age: 0
  name:
    type: sql
    value: DEFAULT # Does not get escaped because of  type: sql
```

This could be done easier:
```yaml
vlad:
  age: 29
  name: Vlad # Gets escaped
dan:
  age: 45
  name: text:Dan # Gets escaped because of text:
robot:
  age: 0
  name: sql:DEFAULT # Does not get escaped because of `sql:` prefix
```

* `text:` or `sql:` does not go to the resulting SQL
* values after the prefix is not trimmed, so the spaces go to SQL
* if no prefix `text:` or `sql:` is specified the value will be interpreted as text and will be escaped
* com.github.vkorobkov.jfixtures.util.RowMergeConflictResolver could be removed
